// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPvsjo4A1CedOP_GN6mnDwQVjRVhmIB8w',
    appId: '1:633774493914:web:a53101e1683c32fe9f15e3',
    messagingSenderId: '633774493914',
    projectId: 'chat-system-fb693',
    authDomain: 'chat-system-fb693.firebaseapp.com',
    storageBucket: 'chat-system-fb693.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDye2VdnZ6YEIRS3tHog9qW3l1k6i3RkZQ',
    appId: '1:633774493914:android:57828946c9ae95b09f15e3',
    messagingSenderId: '633774493914',
    projectId: 'chat-system-fb693',
    storageBucket: 'chat-system-fb693.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn5eVdG4IiRm2oOD7GfVXVWKb89h57jfs',
    appId: '1:633774493914:ios:4bffab052be3bd909f15e3',
    messagingSenderId: '633774493914',
    projectId: 'chat-system-fb693',
    storageBucket: 'chat-system-fb693.appspot.com',
    iosBundleId: 'com.example.chatSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn5eVdG4IiRm2oOD7GfVXVWKb89h57jfs',
    appId: '1:633774493914:ios:5a610f58ee1778cc9f15e3',
    messagingSenderId: '633774493914',
    projectId: 'chat-system-fb693',
    storageBucket: 'chat-system-fb693.appspot.com',
    iosBundleId: 'com.example.chatSystem.RunnerTests',
  );
}
